// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygovlcrytvrbbfngtggn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnb3ZsY3J5dHZyYmJmbmd0Z2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzEzMTMsImV4cCI6MjA3MzAwNzMxM30.RzxYULoqm5OlDXQ-UteIQBDEpqmQG4g_Mr6b5yVAhJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});